os:
  - linux

language: go

dist: trusty

go:
  - 1.7.4

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpcap0.8-dev

script:
  - go test github.com/honeycombio/honeycomb-tcpagent/...
  - go vet ./...

after_success:
  - rm $GOPATH/bin/honeycomb-tcpagent
  - go install -ldflags "-X main.BuildID=1.${TRAVIS_BUILD_NUMBER} -extldflags \"-static\"" github.com/honeycombio/honeycomb-tcpagent/...
  - $GOPATH/bin/honeytail --write_default_config > ./honeycomb-tcpagent.conf
  - ./build-pkg.sh -v "1.${TRAVIS_BUILD_NUMBER}" -t deb
  - ./build-pkg.sh -v "1.${TRAVIS_BUILD_NUMBER}" -t rpm

addons:
    artifacts:
        debug: true
        paths:
        - $GOPATH/bin
